from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import func
from sqlalchemy.orm import Session
from uuid import UUID

from app.core.db import get_db
from app.api.deps import get_current_db_user
from app.models.user import User
from app.models.project import Project
from app.models.canvas import CanvasState
from app.schemas.canvas import CanvasState as CanvasStateSchema, CanvasStateUpdate

router = APIRouter()

def _verify_project_ownership(
    project_id: UUID,
    user_id: UUID,
    db: Session
) -> Project:
    project = db.query(Project).filter(
        Project.id == project_id,
        Project.user_id == user_id
    ).first()
    
    if not project:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Project workspace not found or you do not have permission"
        )
    return project

@router.get("/{project_id}/canvas", response_model=CanvasStateSchema)
def get_project_canvas(
    project_id: UUID,
    current_user: User = Depends(get_current_db_user),
    db: Session = Depends(get_db)
):
    """
    Retrieves the visual graph layout (nodes, edges, node positions)
    representing the High-Level systems layout for React Flow.
    """
    _verify_project_ownership(project_id, current_user.id, db)
    
    canvas = db.query(CanvasState).filter(CanvasState.project_id == project_id).first()
    if not canvas:
        # Return a blank configuration if the orchestrator hasn't finished run
        return CanvasStateSchema(
            id=project_id,  # temporary placeholder ID matching project_id
            project_id=project_id,
            canvas_json={"nodes": [], "edges": [], "viewport": {"x": 0, "y": 0, "zoom": 1}},
            updated_at=datetime.utcnow()
        )
    return canvas

@router.put("/{project_id}/canvas", response_model=CanvasStateSchema)
def update_project_canvas(
    project_id: UUID,
    canvas_in: CanvasStateUpdate,
    current_user: User = Depends(get_current_db_user),
    db: Session = Depends(get_db)
):
    """
    Updates the systems layout representation (nodes, edges) with user manual edits.
    """
    _verify_project_ownership(project_id, current_user.id, db)
    
    canvas = db.query(CanvasState).filter(CanvasState.project_id == project_id).first()
    
    try:
        if not canvas:
            # Create a new canvas layout if not generated by agent design yet
            canvas = CanvasState(
                project_id=project_id,
                canvas_json=canvas_in.canvas_json
            )
            db.add(canvas)
        else:
            canvas.canvas_json = canvas_in.canvas_json
            
        db.commit()
        db.refresh(canvas)
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to update systems canvas state: {str(e)}"
        )
        
    return canvas
