import uuid
import enum
from sqlalchemy import Column, String, DateTime, ForeignKey, func, Enum as SQLEnum, Integer, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from app.core.db import Base

class AgentType(str, enum.Enum):
    PRODUCT = "product"
    SYSTEM_DESIGN = "system_design"
    MARKET = "market"
    FEASIBILITY = "feasibility"
    ROADMAP = "roadmap"

class Page(Base):
    """
    SQLAlchemy model representing individual Notion-style document pages,
    storing structured block contents generated by agents.
    """
    __tablename__ = "pages"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True)
    agent_type = Column(SQLEnum(AgentType, name="agent_type"), nullable=False, index=True)
    title = Column(String(255), nullable=False)
    content_json = Column(JSONB, nullable=False)
    version = Column(Integer, default=1, nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    project = relationship("Project", back_populates="pages")

    __table_args__ = (
        UniqueConstraint("project_id", "agent_type", name="unique_project_agent_page"),
    )
